[package]
name = "peem"
version = "0.1.0"
edition = "2021"
authors = ["Wassim Mansouri <wassim@wassimans.com>"]

[dependencies]
lazy_static = "1.4.0"
once_cell = "1.19.0"
ring = "0.17.8"
sqlx = { version = "0.7.4", features = ["runtime-tokio-rustls", "sqlite"] }
thiserror = "1.0.61"
